### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [Scrum/posthtml-replace#1]
@Damon4 Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by Damon4** [comment]
@Scrum , Приветствую! Прошу прощения за долгий ответ. Конечно, мне интересно и я согласен, если от меня что то нужно, дайте знать.

**Comment by Scrum** [comment]
@Damon4 Доброго дня, мне необходимы права `owner`, что бы я мог переместить данный репозиторий в организацию `posthtml`

**Comment by Damon4** [comment]
@Scrum отправил Transfer ownership

**Comment by Scrum** [comment]
@Damon4 вернул потому что `posthtml already has a repository in the jonathantneal/posthtml-plugin-boilerplate network` - нужно отвязаться от форка

**Comment by Damon4** [comment]
@Scrum смотри Damon4/posthtml-replace2

**Comment by Scrum** [comment]
выслал инвайт

п.с. переименовал в `posthtml-replace`

**Comment by Damon4** [comment]
@Scrum  Либо это косяк гитхаба, либо с не верными правами, но репозиторий у меня отваливается с 500 ошибкой

**Comment by Scrum** [comment]
Github шалит, репо [тут](https://github.com/posthtml/posthtml-replace)

**Comment by Scrum** [comment]
Инвайта незабудьте принять

**Comment by Scrum** [comment]
@Damon4 можно еще права на npm расшарить, сообщество сможет осуществлять поддержку данного репозитория

**Comment by Damon4** [comment]
@Scrum по гитхабу вроде ок, по npm предлагаю с телеграмме списаться, есть ссылка в моем профиле, ну и так же перенести я только за)

**Comment by Scrum** [comment]
@Damon4 переносить не обязательно - достаточно прав, можно на мой акк  `scrum`

**Comment by Damon4** [comment]
@Scrum добавил
